### ISSUE TITLE
Instructions Unclear

### ISSUE THREAD

**Issue by boinary** [CRTC-Computer-Engineering/CRTC-Python-Examples#7]
When first playing I attempted to use `LEFT` or `RIGHT` as the commands. These return errors and often crash the program or says something like " `Thats not something I understand` ". 

When looking around a room, perspective is not maintained. Looking Left tells about a door and a key. but when looking right, tells something that is supposed to be twice to the right. 

`INSOECT` may be a typo of `INSPECT`

**Comment by KenwoodFox** [comment]
Left and right are analogs for north south east and west and this is will be fixed.
You cannot simply `LEFT` and the lobby blurb describes this.
Inspect has now been properly spelled in the blurb though typing `insoect` will also work.

**Comment by boinary** [comment]
as long as the player knows this. make the lobby instructions clearer.
